### ISSUE TITLE
Fabrication and testing?

### ISSUE THREAD

**Issue by acra6488** [p4nd4m01um/team17#5]
Hi, Could we see how testing and fabrication is going, via some notes or images, or a social media page?
-Aurelie -Team 2

**Comment by p4nd4m01um** [comment]
we will do this in the future, but as of now, the sensors have been tested as a standalone system, they're yet to be coupled with the motor circuit and tested as a whole

**Comment by p4nd4m01um** [comment]
the PCB schematics and design files should give you the overall idea of the ongoing progress of the project

**Comment by kenhding** [comment]
Since the PCB still in the process, we cannot perform an entire system test. However, we used LED light to simulate the motor trigger, it works well. The main program and web interface were tested with examples as can be found in the Test demonstration page of WIKI.
The unit test of our project would be done in time.
